// Writes the two result artifacts every run produces: a machine-readable
// qa/results/latest.json (also archived per-run-id) and a human-readable
// QA_LATEST_REPORT.md at the repo root.
import { writeFileSync, mkdirSync } from "fs";
import path from "path";
import { REPO_ROOT } from "./env.mjs";

const RESULTS_DIR = path.join(REPO_ROOT, "qa", "results");

function tally(results) {
  const t = { PASS: 0, FAIL: 0, BLOCKED_NEEDS_SIAM: 0, SKIPPED: 0 };
  for (const r of results) {
    if (t[r.status] !== undefined) t[r.status] += 1;
    else t.SKIPPED += 1;
  }
  return t;
}

export function writeResults(run, resultsByPhase) {
  mkdirSync(RESULTS_DIR, { recursive: true });

  const allResults = Object.values(resultsByPhase).flat();
  const totals = tally(allResults);

  const payload = {
    runId: run.runId,
    mode: run.mode,
    startedAt: run.startedAt,
    completedAt: run.completedAt,
    totals,
    phases: Object.fromEntries(
      Object.entries(resultsByPhase).map(([phaseId, results]) => [
        phaseId,
        { totals: tally(results), checks: results },
      ])
    ),
  };

  writeFileSync(path.join(RESULTS_DIR, "latest.json"), JSON.stringify(payload, null, 2));
  writeFileSync(path.join(RESULTS_DIR, `${run.runId}.json`), JSON.stringify(payload, null, 2));

  writeFileSync(path.join(REPO_ROOT, "QA_LATEST_REPORT.md"), renderMarkdown(payload));

  return payload;
}

function statusIcon(s) {
  return { PASS: "✅", FAIL: "❌", BLOCKED_NEEDS_SIAM: "🚧", SKIPPED: "⏭️" }[s] ?? "❓";
}

function renderMarkdown(payload) {
  const lines = [];
  lines.push(`# InkBook QA Engine — Latest Report`);
  lines.push("");
  lines.push(`**Run:** \`${payload.runId}\` · **Mode:** \`${payload.mode}\` · **Started:** ${payload.startedAt} · **Completed:** ${payload.completedAt ?? "(in progress / interrupted)"}`);
  lines.push("");
  lines.push(`## Totals`);
  lines.push("");
  lines.push(`| PASS | FAIL | BLOCKED_NEEDS_SIAM | SKIPPED |`);
  lines.push(`|---|---|---|---|`);
  lines.push(`| ${payload.totals.PASS} | ${payload.totals.FAIL} | ${payload.totals.BLOCKED_NEEDS_SIAM} | ${payload.totals.SKIPPED} |`);
  lines.push("");

  for (const [phaseId, phase] of Object.entries(payload.phases)) {
    lines.push(`## ${phaseId}`);
    lines.push("");
    lines.push(`${phase.totals.PASS} PASS, ${phase.totals.FAIL} FAIL, ${phase.totals.BLOCKED_NEEDS_SIAM} BLOCKED, ${phase.totals.SKIPPED} SKIPPED`);
    lines.push("");
    if (phase.checks.length > 0) {
      lines.push(`| Check | Status | Duration | Note |`);
      lines.push(`|---|---|---|---|`);
      for (const c of phase.checks) {
        const note = (c.reason ?? "").replace(/\|/g, "\\|").replace(/\n/g, " ").slice(0, 200);
        lines.push(`| ${c.label ?? c.id} | ${statusIcon(c.status)} ${c.status} | ${c.durationMs ? Math.round(c.durationMs / 1000) + "s" : ""} | ${note} |`);
      }
      lines.push("");
    }
  }

  const failures = Object.values(payload.phases).flatMap((p) => p.checks).filter((c) => c.status === "FAIL");
  const blocked = Object.values(payload.phases).flatMap((p) => p.checks).filter((c) => c.status === "BLOCKED_NEEDS_SIAM");

  if (failures.length > 0) {
    lines.push(`## Failures requiring attention`);
    lines.push("");
    for (const f of failures) {
      lines.push(`### ${f.label ?? f.id}`);
      lines.push(`**Reason:** ${f.reason ?? "unknown"}`);
      if (f.stderr) lines.push("```\n" + f.stderr.slice(-1500) + "\n```");
      lines.push("");
    }
  }

  if (blocked.length > 0) {
    lines.push(`## BLOCKED_NEEDS_SIAM`);
    lines.push("");
    for (const b of blocked) {
      lines.push(`- **${b.label ?? b.id}** — ${b.reason}`);
    }
    lines.push("");
  }

  lines.push(`---`);
  lines.push(`*Generated by the InkBook QA Engine (\`npm run qa:inkbook\`). See QA_ENGINE.md for architecture and qa/manifest.json for full test surface coverage.*`);

  return lines.join("\n");
}
